apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: prod-applications
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-applications
  template:
    metadata:
      labels:
        app: prod-applications
    spec:
      containers:
        - name: prod-echo-service
          image: kursornn/prod-echo-service:0.0.2
          ports:
            - containerPort: 8080
              protocol: TCP