apiVersion: v1
kind: Service
metadata: 
  name: prod-application-svc
  namespace: default
spec:
  selector:
    app: prod-applications
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP